[tool.poetry]
name = "certylex"
version = "0.1.0"
description = "This project is designed to implement neural networks and LLMs to analyze legal documents."
authors = ["0xGeN02 <manuelmateodgl02@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
